name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: install
        run: bun i
      - name: biome
        run: bun ci

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: install
        run: bun i
      - name: build
        run: bun run build
